//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class ApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: RegisterModel | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Account/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginModel | undefined): Promise<LoginResult> {
        let url_ = this.baseUrl + "/api/Account/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<LoginResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LoginResult.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LoginResult>(null as any);
    }

    /**
     * @return OK
     */
    logout(): Promise<void> {
        let url_ = this.baseUrl + "/api/Account/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogout(_response);
        });
    }

    protected processLogout(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    validate(): Promise<ValidateResult> {
        let url_ = this.baseUrl + "/api/Account/validate";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processValidate(_response);
        });
    }

    protected processValidate(response: Response): Promise<ValidateResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ValidateResult.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ValidateResult>(null as any);
    }

    /**
     * @return OK
     */
    getFoods(): Promise<FoodDTO[]> {
        let url_ = this.baseUrl + "/api/Diary/GetFoods";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFoods(_response);
        });
    }

    protected processGetFoods(response: Response): Promise<FoodDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(FoodDTO.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FoodDTO[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addFood(body: CreateFoodDTO | undefined): Promise<FoodDTO> {
        let url_ = this.baseUrl + "/api/Diary/AddFood";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddFood(_response);
        });
    }

    protected processAddFood(response: Response): Promise<FoodDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FoodDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FoodDTO>(null as any);
    }

    /**
     * @param date (optional) 
     * @return OK
     */
    getFoodEntries(date: Date | undefined): Promise<FoodEntryDTO[]> {
        let url_ = this.baseUrl + "/api/Diary/GetFoodEntries?";
        if (date === null)
            throw new globalThis.Error("The parameter 'date' cannot be null.");
        else if (date !== undefined)
            url_ += "date=" + encodeURIComponent(date ? "" + date.toISOString() : "") + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFoodEntries(_response);
        });
    }

    protected processGetFoodEntries(response: Response): Promise<FoodEntryDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(FoodEntryDTO.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FoodEntryDTO[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addFoodEntry(body: CreateFoodEntryDTO | undefined): Promise<FoodEntryDTO> {
        let url_ = this.baseUrl + "/api/Diary/AddFoodEntry";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddFoodEntry(_response);
        });
    }

    protected processAddFoodEntry(response: Response): Promise<FoodEntryDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FoodEntryDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FoodEntryDTO>(null as any);
    }

    /**
     * @return OK
     */
    deleteFoodEntry(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Diary/DeleteFoodEntry/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteFoodEntry(_response);
        });
    }

    protected processDeleteFoodEntry(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param date (optional) 
     * @return OK
     */
    getWaterEntries(date: Date | undefined): Promise<WaterEntryDTO[]> {
        let url_ = this.baseUrl + "/api/Diary/GetWaterEntries?";
        if (date === null)
            throw new globalThis.Error("The parameter 'date' cannot be null.");
        else if (date !== undefined)
            url_ += "date=" + encodeURIComponent(date ? "" + date.toISOString() : "") + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetWaterEntries(_response);
        });
    }

    protected processGetWaterEntries(response: Response): Promise<WaterEntryDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(WaterEntryDTO.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WaterEntryDTO[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addWaterEntry(body: CreateWaterEntryDTO | undefined): Promise<WaterEntryDTO> {
        let url_ = this.baseUrl + "/api/Diary/AddWaterEntry";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddWaterEntry(_response);
        });
    }

    protected processAddWaterEntry(response: Response): Promise<WaterEntryDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WaterEntryDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WaterEntryDTO>(null as any);
    }

    /**
     * @return OK
     */
    deleteWaterEntry(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/Diary/DeleteWaterEntry/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteWaterEntry(_response);
        });
    }

    protected processDeleteWaterEntry(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getMealPlans(): Promise<MealPlanDTO[]> {
        let url_ = this.baseUrl + "/api/Plans/GetMealPlans";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetMealPlans(_response);
        });
    }

    protected processGetMealPlans(response: Response): Promise<MealPlanDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(MealPlanDTO.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MealPlanDTO[]>(null as any);
    }

    /**
     * @return OK
     */
    getMealPlan(id: number): Promise<MealPlanDTO> {
        let url_ = this.baseUrl + "/api/Plans/GetMealPlan/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetMealPlan(_response);
        });
    }

    protected processGetMealPlan(response: Response): Promise<MealPlanDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MealPlanDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MealPlanDTO>(null as any);
    }

    /**
     * @param mealPlanId (optional) 
     * @return OK
     */
    selectMealPlan(mealPlanId: number | undefined, id: string): Promise<UserDTO> {
        let url_ = this.baseUrl + "/api/Plans/SelectMealPlan/{id}?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (mealPlanId === null)
            throw new globalThis.Error("The parameter 'mealPlanId' cannot be null.");
        else if (mealPlanId !== undefined)
            url_ += "mealPlanId=" + encodeURIComponent("" + mealPlanId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "PUT",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSelectMealPlan(_response);
        });
    }

    protected processSelectMealPlan(response: Response): Promise<UserDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserDTO.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserDTO>(null as any);
    }
}

export class CreateFoodDTO implements ICreateFoodDTO {
    name?: string | undefined;
    engName?: string | undefined;
    calories?: number;
    protein?: number;
    fat?: number;
    carbs?: number;
    userId?: string | undefined;

    constructor(data?: ICreateFoodDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.engName = _data["engName"];
            this.calories = _data["calories"];
            this.protein = _data["protein"];
            this.fat = _data["fat"];
            this.carbs = _data["carbs"];
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): CreateFoodDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CreateFoodDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["engName"] = this.engName;
        data["calories"] = this.calories;
        data["protein"] = this.protein;
        data["fat"] = this.fat;
        data["carbs"] = this.carbs;
        data["userId"] = this.userId;
        return data;
    }
}

export interface ICreateFoodDTO {
    name?: string | undefined;
    engName?: string | undefined;
    calories?: number;
    protein?: number;
    fat?: number;
    carbs?: number;
    userId?: string | undefined;
}

export class CreateFoodEntryDTO implements ICreateFoodEntryDTO {
    date?: Date;
    weight?: number;
    foodId?: number;
    mealTypeId?: number;
    userId?: string | undefined;

    constructor(data?: ICreateFoodEntryDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : undefined as any;
            this.weight = _data["weight"];
            this.foodId = _data["foodId"];
            this.mealTypeId = _data["mealTypeId"];
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): CreateFoodEntryDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CreateFoodEntryDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? this.date.toISOString() : undefined as any;
        data["weight"] = this.weight;
        data["foodId"] = this.foodId;
        data["mealTypeId"] = this.mealTypeId;
        data["userId"] = this.userId;
        return data;
    }
}

export interface ICreateFoodEntryDTO {
    date?: Date;
    weight?: number;
    foodId?: number;
    mealTypeId?: number;
    userId?: string | undefined;
}

export class CreateWaterEntryDTO implements ICreateWaterEntryDTO {
    date?: Date;
    amount?: number;
    userId?: string | undefined;

    constructor(data?: ICreateWaterEntryDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.date = _data["date"] ? new Date(_data["date"].toString()) : undefined as any;
            this.amount = _data["amount"];
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): CreateWaterEntryDTO {
        data = typeof data === 'object' ? data : {};
        let result = new CreateWaterEntryDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["date"] = this.date ? this.date.toISOString() : undefined as any;
        data["amount"] = this.amount;
        data["userId"] = this.userId;
        return data;
    }
}

export interface ICreateWaterEntryDTO {
    date?: Date;
    amount?: number;
    userId?: string | undefined;
}

export class FoodDTO implements IFoodDTO {
    id?: number;
    name?: string | undefined;
    engName?: string | undefined;
    calories?: number;
    protein?: number;
    fat?: number;
    carbs?: number;

    constructor(data?: IFoodDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.engName = _data["engName"];
            this.calories = _data["calories"];
            this.protein = _data["protein"];
            this.fat = _data["fat"];
            this.carbs = _data["carbs"];
        }
    }

    static fromJS(data: any): FoodDTO {
        data = typeof data === 'object' ? data : {};
        let result = new FoodDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["engName"] = this.engName;
        data["calories"] = this.calories;
        data["protein"] = this.protein;
        data["fat"] = this.fat;
        data["carbs"] = this.carbs;
        return data;
    }
}

export interface IFoodDTO {
    id?: number;
    name?: string | undefined;
    engName?: string | undefined;
    calories?: number;
    protein?: number;
    fat?: number;
    carbs?: number;
}

export class FoodEntryDTO implements IFoodEntryDTO {
    id?: number;
    date?: Date;
    weight?: number;
    foodId?: number;
    mealTypeId?: number;
    userId?: string | undefined;
    food?: FoodDTO;
    mealType?: MealType;

    constructor(data?: IFoodEntryDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : undefined as any;
            this.weight = _data["weight"];
            this.foodId = _data["foodId"];
            this.mealTypeId = _data["mealTypeId"];
            this.userId = _data["userId"];
            this.food = _data["food"] ? FoodDTO.fromJS(_data["food"]) : undefined as any;
            this.mealType = _data["mealType"] ? MealType.fromJS(_data["mealType"]) : undefined as any;
        }
    }

    static fromJS(data: any): FoodEntryDTO {
        data = typeof data === 'object' ? data : {};
        let result = new FoodEntryDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : undefined as any;
        data["weight"] = this.weight;
        data["foodId"] = this.foodId;
        data["mealTypeId"] = this.mealTypeId;
        data["userId"] = this.userId;
        data["food"] = this.food ? this.food.toJSON() : undefined as any;
        data["mealType"] = this.mealType ? this.mealType.toJSON() : undefined as any;
        return data;
    }
}

export interface IFoodEntryDTO {
    id?: number;
    date?: Date;
    weight?: number;
    foodId?: number;
    mealTypeId?: number;
    userId?: string | undefined;
    food?: FoodDTO;
    mealType?: MealType;
}

export class LoginModel implements ILoginModel {
    userName?: string | undefined;
    password?: string | undefined;

    constructor(data?: ILoginModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginModel {
        data = typeof data === 'object' ? data : {};
        let result = new LoginModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginModel {
    userName?: string | undefined;
    password?: string | undefined;
}

export class LoginResult implements ILoginResult {
    token?: string | undefined;
    userName?: string | undefined;
    userRole?: string | undefined;

    constructor(data?: ILoginResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.token = _data["token"];
            this.userName = _data["userName"];
            this.userRole = _data["userRole"];
        }
    }

    static fromJS(data: any): LoginResult {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["token"] = this.token;
        data["userName"] = this.userName;
        data["userRole"] = this.userRole;
        return data;
    }
}

export interface ILoginResult {
    token?: string | undefined;
    userName?: string | undefined;
    userRole?: string | undefined;
}

export class MealPlan implements IMealPlan {
    id?: number;
    title?: string | undefined;
    description?: string | undefined;
    fullDescription?: string | undefined;
    benefitsJson?: string | undefined;
    warningsJson?: string | undefined;
    calories?: string | undefined;
    protein?: string | undefined;
    fat?: string | undefined;
    carbs?: string | undefined;

    constructor(data?: IMealPlan) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.fullDescription = _data["fullDescription"];
            this.benefitsJson = _data["benefitsJson"];
            this.warningsJson = _data["warningsJson"];
            this.calories = _data["calories"];
            this.protein = _data["protein"];
            this.fat = _data["fat"];
            this.carbs = _data["carbs"];
        }
    }

    static fromJS(data: any): MealPlan {
        data = typeof data === 'object' ? data : {};
        let result = new MealPlan();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["fullDescription"] = this.fullDescription;
        data["benefitsJson"] = this.benefitsJson;
        data["warningsJson"] = this.warningsJson;
        data["calories"] = this.calories;
        data["protein"] = this.protein;
        data["fat"] = this.fat;
        data["carbs"] = this.carbs;
        return data;
    }
}

export interface IMealPlan {
    id?: number;
    title?: string | undefined;
    description?: string | undefined;
    fullDescription?: string | undefined;
    benefitsJson?: string | undefined;
    warningsJson?: string | undefined;
    calories?: string | undefined;
    protein?: string | undefined;
    fat?: string | undefined;
    carbs?: string | undefined;
}

export class MealPlanDTO implements IMealPlanDTO {
    id?: number;
    title?: string | undefined;
    description?: string | undefined;
    fullDescription?: string | undefined;
    benefits?: string[] | undefined;
    warnings?: string[] | undefined;
    calories?: string | undefined;
    protein?: string | undefined;
    fat?: string | undefined;
    carbs?: string | undefined;
    mealPlanDay?: MealPlanDayDTO[] | undefined;

    constructor(data?: IMealPlanDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.description = _data["description"];
            this.fullDescription = _data["fullDescription"];
            if (Array.isArray(_data["benefits"])) {
                this.benefits = [] as any;
                for (let item of _data["benefits"])
                    this.benefits!.push(item);
            }
            if (Array.isArray(_data["warnings"])) {
                this.warnings = [] as any;
                for (let item of _data["warnings"])
                    this.warnings!.push(item);
            }
            this.calories = _data["calories"];
            this.protein = _data["protein"];
            this.fat = _data["fat"];
            this.carbs = _data["carbs"];
            if (Array.isArray(_data["mealPlanDay"])) {
                this.mealPlanDay = [] as any;
                for (let item of _data["mealPlanDay"])
                    this.mealPlanDay!.push(MealPlanDayDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): MealPlanDTO {
        data = typeof data === 'object' ? data : {};
        let result = new MealPlanDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["description"] = this.description;
        data["fullDescription"] = this.fullDescription;
        if (Array.isArray(this.benefits)) {
            data["benefits"] = [];
            for (let item of this.benefits)
                data["benefits"].push(item);
        }
        if (Array.isArray(this.warnings)) {
            data["warnings"] = [];
            for (let item of this.warnings)
                data["warnings"].push(item);
        }
        data["calories"] = this.calories;
        data["protein"] = this.protein;
        data["fat"] = this.fat;
        data["carbs"] = this.carbs;
        if (Array.isArray(this.mealPlanDay)) {
            data["mealPlanDay"] = [];
            for (let item of this.mealPlanDay)
                data["mealPlanDay"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IMealPlanDTO {
    id?: number;
    title?: string | undefined;
    description?: string | undefined;
    fullDescription?: string | undefined;
    benefits?: string[] | undefined;
    warnings?: string[] | undefined;
    calories?: string | undefined;
    protein?: string | undefined;
    fat?: string | undefined;
    carbs?: string | undefined;
    mealPlanDay?: MealPlanDayDTO[] | undefined;
}

export class MealPlanDayDTO implements IMealPlanDayDTO {
    id?: number;
    day?: number;
    breakfast?: string | undefined;
    lunch?: string | undefined;
    dinner?: string | undefined;
    snacks?: string | undefined;
    mealPlanId?: number;

    constructor(data?: IMealPlanDayDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.day = _data["day"];
            this.breakfast = _data["breakfast"];
            this.lunch = _data["lunch"];
            this.dinner = _data["dinner"];
            this.snacks = _data["snacks"];
            this.mealPlanId = _data["mealPlanId"];
        }
    }

    static fromJS(data: any): MealPlanDayDTO {
        data = typeof data === 'object' ? data : {};
        let result = new MealPlanDayDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["day"] = this.day;
        data["breakfast"] = this.breakfast;
        data["lunch"] = this.lunch;
        data["dinner"] = this.dinner;
        data["snacks"] = this.snacks;
        data["mealPlanId"] = this.mealPlanId;
        return data;
    }
}

export interface IMealPlanDayDTO {
    id?: number;
    day?: number;
    breakfast?: string | undefined;
    lunch?: string | undefined;
    dinner?: string | undefined;
    snacks?: string | undefined;
    mealPlanId?: number;
}

export class MealType implements IMealType {
    id?: number;
    name?: string | undefined;

    constructor(data?: IMealType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): MealType {
        data = typeof data === 'object' ? data : {};
        let result = new MealType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IMealType {
    id?: number;
    name?: string | undefined;
}

export class RegisterModel implements IRegisterModel {
    fullName?: string | undefined;
    userName?: string | undefined;
    password?: string | undefined;

    constructor(data?: IRegisterModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.fullName = _data["fullName"];
            this.userName = _data["userName"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): RegisterModel {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fullName"] = this.fullName;
        data["userName"] = this.userName;
        data["password"] = this.password;
        return data;
    }
}

export interface IRegisterModel {
    fullName?: string | undefined;
    userName?: string | undefined;
    password?: string | undefined;
}

export class UserDTO implements IUserDTO {
    id?: string | undefined;
    fullName?: string | undefined;
    mealPlanStart?: Date;
    mealPlanId?: number | undefined;
    mealPlan?: MealPlan;
    food?: FoodDTO[] | undefined;
    foodEntry?: FoodEntryDTO[] | undefined;
    waterEntry?: WaterEntryDTO[] | undefined;

    constructor(data?: IUserDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.fullName = _data["fullName"];
            this.mealPlanStart = _data["mealPlanStart"] ? new Date(_data["mealPlanStart"].toString()) : undefined as any;
            this.mealPlanId = _data["mealPlanId"];
            this.mealPlan = _data["mealPlan"] ? MealPlan.fromJS(_data["mealPlan"]) : undefined as any;
            if (Array.isArray(_data["food"])) {
                this.food = [] as any;
                for (let item of _data["food"])
                    this.food!.push(FoodDTO.fromJS(item));
            }
            if (Array.isArray(_data["foodEntry"])) {
                this.foodEntry = [] as any;
                for (let item of _data["foodEntry"])
                    this.foodEntry!.push(FoodEntryDTO.fromJS(item));
            }
            if (Array.isArray(_data["waterEntry"])) {
                this.waterEntry = [] as any;
                for (let item of _data["waterEntry"])
                    this.waterEntry!.push(WaterEntryDTO.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UserDTO {
        data = typeof data === 'object' ? data : {};
        let result = new UserDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["fullName"] = this.fullName;
        data["mealPlanStart"] = this.mealPlanStart ? this.mealPlanStart.toISOString() : undefined as any;
        data["mealPlanId"] = this.mealPlanId;
        data["mealPlan"] = this.mealPlan ? this.mealPlan.toJSON() : undefined as any;
        if (Array.isArray(this.food)) {
            data["food"] = [];
            for (let item of this.food)
                data["food"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.foodEntry)) {
            data["foodEntry"] = [];
            for (let item of this.foodEntry)
                data["foodEntry"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.waterEntry)) {
            data["waterEntry"] = [];
            for (let item of this.waterEntry)
                data["waterEntry"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUserDTO {
    id?: string | undefined;
    fullName?: string | undefined;
    mealPlanStart?: Date;
    mealPlanId?: number | undefined;
    mealPlan?: MealPlan;
    food?: FoodDTO[] | undefined;
    foodEntry?: FoodEntryDTO[] | undefined;
    waterEntry?: WaterEntryDTO[] | undefined;
}

export class ValidateResult implements IValidateResult {
    message?: string | undefined;
    userName?: string | undefined;
    userRole?: string | undefined;

    constructor(data?: IValidateResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.message = _data["message"];
            this.userName = _data["userName"];
            this.userRole = _data["userRole"];
        }
    }

    static fromJS(data: any): ValidateResult {
        data = typeof data === 'object' ? data : {};
        let result = new ValidateResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["message"] = this.message;
        data["userName"] = this.userName;
        data["userRole"] = this.userRole;
        return data;
    }
}

export interface IValidateResult {
    message?: string | undefined;
    userName?: string | undefined;
    userRole?: string | undefined;
}

export class WaterEntryDTO implements IWaterEntryDTO {
    id?: number;
    date?: Date;
    amount?: number;
    userId?: string | undefined;

    constructor(data?: IWaterEntryDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : undefined as any;
            this.amount = _data["amount"];
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): WaterEntryDTO {
        data = typeof data === 'object' ? data : {};
        let result = new WaterEntryDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["date"] = this.date ? this.date.toISOString() : undefined as any;
        data["amount"] = this.amount;
        data["userId"] = this.userId;
        return data;
    }
}

export interface IWaterEntryDTO {
    id?: number;
    date?: Date;
    amount?: number;
    userId?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}